### ISSUE TITLE
CfA datasets not uploaded to Huggingface

### ISSUE THREAD

**Issue by ado8** [MultimodalUniverse/MultimodalUniverse#124]
The upload_to_hub.py script does not upload the four CfA datasets.
I suspect it's because the individual datasets (cfa3, cfa4, cfa_snII, cfa3_4sh) do not match the directory name (cfa), such that the lines
```
 31     # Copy the file to the destination folder
 32     shutil.copyfile(f"./{dataset}/{dataset}.py",
 33                     f"{destination_folder}/{dataset}/{dataset}.py")
 34     print("Copied file:", f"{dataset}/{dataset}.py")
```
do not point to real paths.

**Comment by mb010** [comment]
@ado8 my plan is to adapt the dataset to have subdatasets and an 'all' dataset for cfa. Let me know if you think that won't work, otherwise I'll refactor it tomorrow or Thursday. 

The SDSS data is formatted to do this, see lines 80 - 127 of [this file](https://github.com/MultimodalUniverse/MultimodalUniverse/blob/864452cb955464169ae889184f7656a5c0a1de04/scripts/sdss/sdss.py#L80).
